### ISSUE TITLE
Retriving Models from Anthropic API

### ISSUE THREAD

**Issue by hra42** [kevinhermawan/swift-llm-chat-anthropic#2]
How do you currently get the models from the Anthropic API? I don't find a function like the openAI package from you has:
```swift
let openAI = LLMChatOpenAI(apiKey: appState.openAIApiKey)
let models = try await openAI.models()
await MainActor.run {
    self.availableModels = models.data.map { $0.id }
}
```

**Comment by kevinhermawan** [comment]
Hi @hra42, I recently published a new package called [swift-ai-model-retriever](https://github.com/kevinhermawan/swift-ai-model-retriever) to handle this task. In the future release of `swift-llm-chat-openai`, I’ll remove the `models` method, so please use this package instead.

**Comment by hra42** [comment]
Ahh, I see, brilliant solution! Thank you!
